OLED_ENABLE = yes
RGB_MATRIX_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes

SRC += oled.c

BOOTLOADER = atmel-dfu

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
KEY_OVERRIDE_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no

